#
#  Copyright (C)  2014 George Wong
#  GNU General Public License
#

all:
	javac PathFinder.java

run:
	java PathFinder

jar:
	javac PathFinder.java
	jar cfm PathFinder.jar Manifest.txt *.class

clean:
	rm -f *.class
	rm -f PathFinder.jar
